"""Evaluate retrieval quality using RAGAS metrics.

Loads the synthetic testset from eval/testset.jsonl (generated by
eval_dataset.py), runs each question through a retriever + LLM,
and scores the results with RAGAS metrics.

Run baseline (dense-only):   python -m macro_mate.evaluate --mode dense
Run improved (ensemble):     python -m macro_mate.evaluate --mode ensemble
"""

import argparse
import time

import pandas as pd
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from ragas import EvaluationDataset, evaluate, RunConfig
from ragas.llms import LangchainLLMWrapper
from ragas.metrics import (
    LLMContextRecall,
    LLMContextPrecisionWithReference,
    Faithfulness,
    FactualCorrectness,
    ResponseRelevancy,
)

from macro_mate.config import LLM_MODEL, COHERE_API_KEY
from macro_mate.data_loader import load_all_documents
from macro_mate.vector_store import create_vector_store
from macro_mate.retrievers import (
    create_dense_retriever,
    create_ensemble_retriever,
    create_reranked_ensemble_retriever,
)
from macro_mate.eval_dataset import TESTSET_PATH, EVAL_DIR


RAG_PROMPT = ChatPromptTemplate.from_template(
    "You are a helpful assistant who answers questions based on provided "
    "context. You must only use the provided context, and cannot use your "
    "own knowledge.\n\n"
    "### Question\n{question}\n\n"
    "### Context\n{context}"
)


def load_testset() -> pd.DataFrame:
    """Load the JSONL testset that eval_dataset.py saved to disk."""
    return pd.read_json(TESTSET_PATH, orient="records", lines=True)


def build_retriever(mode: str):
    """Build the data pipeline and return the requested retriever."""
    print(f"[Eval] Building {mode} retriever …")
    documents = load_all_documents()
    vector_store = create_vector_store(documents)

    if mode == "dense":
        return create_dense_retriever(vector_store)
    elif mode == "reranked":
        if not COHERE_API_KEY:
            print("[Eval] WARNING: COHERE_API_KEY not set. Falling back to ensemble.")
            return create_ensemble_retriever(vector_store, documents)
        return create_reranked_ensemble_retriever(
            vector_store, documents, COHERE_API_KEY
        )
    else:
        return create_ensemble_retriever(vector_store, documents)


def run_evaluation(mode: str):
    """Run the full RAGAS evaluation pipeline."""
    dataset = load_testset()
    retriever = build_retriever(mode)
    llm = ChatOpenAI(model=LLM_MODEL, temperature=0)

    print(f"[Eval] Running {len(dataset)} questions through {mode} retriever …")

    responses = []
    contexts = []

    for i, row in dataset.iterrows():
        question = row["user_input"]
        docs = retriever.invoke(question)
        retrieved_texts = [doc.page_content for doc in docs]
        docs_content = "\n\n".join(retrieved_texts)
        messages = RAG_PROMPT.format_messages(question=question, context=docs_content)
        response = llm.invoke(messages)
        responses.append(response.content)
        contexts.append(retrieved_texts)
        print(f"  [{i+1}/{len(dataset)}] {question[:60]}…")
        time.sleep(1)

    dataset["response"] = responses
    dataset["retrieved_contexts"] = contexts

    eval_cols = ["user_input", "response", "retrieved_contexts", "reference", "reference_contexts"]
    eval_df = dataset[[c for c in eval_cols if c in dataset.columns]].copy()
    eval_df = eval_df.where(eval_df.notna(), None)

    evaluation_dataset = EvaluationDataset.from_pandas(eval_df)
    evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model=LLM_MODEL))

    print(f"\n[Eval] Scoring with RAGAS metrics …")
    result = evaluate(
        dataset=evaluation_dataset,
        metrics=[
            Faithfulness(),
            LLMContextPrecisionWithReference(),
            LLMContextRecall(),
            FactualCorrectness(),
            ResponseRelevancy(),
        ],
        llm=evaluator_llm,
        run_config=RunConfig(timeout=360),
    )

    print(f"\n[Eval] {mode.upper()} results:")
    print(result)

    result.to_pandas().to_csv(EVAL_DIR / f"{mode}_results.csv", index=False)
    print(f"[Eval] Saved detailed results to {EVAL_DIR / f'{mode}_results.csv'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate MacroMind retrieval")
    parser.add_argument(
        "--mode",
        choices=["dense", "ensemble", "reranked"],
        default="dense",
        help="Retriever mode: 'dense' for baseline, 'ensemble' for improved, 'reranked' for Cohere reranked",
    )
    args = parser.parse_args()
    run_evaluation(args.mode)
